name: eyelevel-secret-credentials
namespace: eyelevel

data:
  GROUNDX_ADMIN_EMAIL: support@myco.net
  GROUNDX_ADMIN_API_KEY: 00000000-0000-0000-0000-000000000001
  GROUNDX_ADMIN_PASSWORD: password
  GROUNDX_ADMIN_USERNAME: 00000000-0000-0000-0000-000000000000
  GROUNDX_AGENT_API_KEY: LLM_API_KEY
  GROUNDX_LICENSE_KEY: 00000000-0000-0000-0000-000000000002
  MYSQL_INIT_PASSWORD: password
  MYSQL_INIT_USER: root
  MYSQL_USER: eyelevel
  MYSQL_PASSWORD: password