{{- if .Values.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "billing-operators.fullname" . }}
  labels:
    {{- include "billing-operators.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.serviceAccount.clusterRole }}
subjects:
  - kind: ServiceAccount
    name: {{ include "billing-operators.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
