{{/*
Declarative equivalent of:
  oc adm policy add-scc-to-user anyuid -z minio-tenant-sa -n $project
*/}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "billing-operators.fullname" . }}-minio-tenant-anyuid
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "billing-operators.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
  - kind: ServiceAccount
    name: minio-tenant-sa
    namespace: {{ .Release.Namespace }}
