{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "billing-operators.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "billing-operators.labels" . | nindent 4 }}
{{- end }}
