{{- if .Values.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "billing-workloads.fullname" . }}
  labels:
    {{- include "billing-workloads.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-delete
    "helm.sh/hook-weight": "-15"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.serviceAccount.clusterRole }}
subjects:
  - kind: ServiceAccount
    name: {{ include "billing-workloads.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
