{{/*
Declarative equivalent of:
  oc expose svc/minio-tenant-console -n $project
*/}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: minio-tenant-console
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "billing-workloads.labels" . | nindent 4 }}
spec:
  to:
    kind: Service
    name: minio-tenant-console
    weight: 100
  wildcardPolicy: None
