{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "billing-workloads.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "billing-workloads.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-delete
    "helm.sh/hook-weight": "-15"
{{- end }}
